#!/usr/bin/env python3
import argparse
import json
import random
from typing import Any

from api_bot_lib import ApiClient


SUBURBS = ["Surry Hills", "Redfern", "Newtown", "Marrickville"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Seed BarkWise API with synthetic providers and community posts.")
    parser.add_argument("--base-url", default="http://localhost:8000", help="API base URL.")
    parser.add_argument("--users", default="user_1,user_2,user_3", help="Comma-separated user IDs.")
    parser.add_argument("--password", default="petsocial-demo", help="Login password for all users.")
    parser.add_argument("--providers-per-user", type=int, default=1, help="Providers to create for each user.")
    parser.add_argument("--group-posts-per-user", type=int, default=2, help="Group posts to create for each user.")
    parser.add_argument("--lost-found-per-user", type=int, default=1, help="Lost/found posts to create for each user.")
    parser.add_argument("--seed", type=int, default=7, help="Random seed.")
    return parser.parse_args()


def _create_provider(client: ApiClient, user_id: str, idx: int, rand: random.Random) -> dict[str, Any]:
    payload = {
        "user_id": user_id,
        "name": f"Seeded Listing {user_id}-{idx}",
        "category": rand.choice(["dog_walking", "grooming"]),
        "suburb": rand.choice(SUBURBS),
        "description": "Synthetic provider seeded for QA/test bot activity.",
        "price_from": rand.randint(20, 65),
    }
    result = client.request("POST", "/services/providers", json_body=payload)
    return {"ok": result.ok, "status": result.status_code, "payload": result.body}


def _create_group_post(client: ApiClient, user_id: str, idx: int, rand: random.Random) -> dict[str, Any]:
    payload = {
        "type": "group_post",
        "user_id": user_id,
        "title": f"Seeded community update {user_id}-{idx}",
        "body": "Synthetic post generated by api_bot_seed_activity.py",
        "suburb": rand.choice(SUBURBS),
    }
    result = client.request("POST", "/community/posts", json_body=payload)
    return {"ok": result.ok, "status": result.status_code, "payload": result.body}


def _create_lost_found(client: ApiClient, user_id: str, idx: int, rand: random.Random) -> dict[str, Any]:
    alert_type = rand.choice(["lost", "found"])
    payload = {
        "type": "lost_found",
        "user_id": user_id,
        "title": f"Seeded {alert_type} alert {user_id}-{idx}",
        "body": "Synthetic lost/found alert generated for test scenarios.",
        "suburb": rand.choice(SUBURBS),
        "alert_type": alert_type,
        "pet_name": rand.choice(["Milo", "Luna", "Coco", "Mochi"]),
        "pet_traits": "Friendly, wearing harness",
        "last_seen_location": "Main park",
        "contact_pref": "In-app message",
    }
    result = client.request("POST", "/community/posts", json_body=payload)
    return {"ok": result.ok, "status": result.status_code, "payload": result.body}


def main() -> int:
    args = parse_args()
    users = [item.strip() for item in args.users.split(",") if item.strip()]
    if not users:
        raise SystemExit("At least one user is required")

    rand = random.Random(args.seed)
    summary: dict[str, Any] = {"base_url": args.base_url, "users": {}}
    has_error = False

    for user_id in users:
        client = ApiClient(base_url=args.base_url)
        login = client.login(user_id=user_id, password=args.password)
        user_result: dict[str, Any] = {
            "login": {"ok": login.ok, "status": login.status_code, "payload": login.body},
            "providers": [],
            "group_posts": [],
            "lost_found": [],
        }
        if not login.ok:
            summary["users"][user_id] = user_result
            has_error = True
            continue

        for idx in range(args.providers_per_user):
            created = _create_provider(client, user_id, idx, rand)
            user_result["providers"].append(created)
            has_error = has_error or (not created["ok"])

        for idx in range(args.group_posts_per_user):
            created = _create_group_post(client, user_id, idx, rand)
            user_result["group_posts"].append(created)
            has_error = has_error or (not created["ok"])

        for idx in range(args.lost_found_per_user):
            created = _create_lost_found(client, user_id, idx, rand)
            user_result["lost_found"].append(created)
            has_error = has_error or (not created["ok"])

        summary["users"][user_id] = user_result

    print(json.dumps(summary, indent=2, sort_keys=True))
    return 2 if has_error else 0


if __name__ == "__main__":
    raise SystemExit(main())
